spring:
  # 数据库连接信息
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/smart_admin_v2_prod?autoReconnect=true&useServerPreparedStmts=false&rewriteBatchedStatements=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: Zhuoda123456
    initial-size: 10
    min-idle: 10
    max-active: 100
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    druid:
      username: druid
      password: 1024
      login:
        enabled: true
      method:
        pointcut: net.lab1024.sa..*Service.*

  # mvc swagger bugfix
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # redis 连接池配置信息
  redis:
    database: 1
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 100
        min-idle: 10
        max-idle: 10
        max-wait: 30000ms
    port: 6379
    timeout: 10000ms
    password:

  # 上传文件大小配置
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  # json序列化相关配置
  jackson:
    serialization:
      write-enums-using-to-string: true
      write-dates-as-timestamps: false
    deserialization:
      read-enums-using-to-string: true
      fail-on-unknown-properties: false
    default-property-inclusion: always
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # 缓存实现类型
  cache:
    type: caffeine

# tomcat 配置，主要用于 配置 访问日志（便于将来排查错误）
server:
  tomcat:
    basedir: ${localPath:/home}/logs/smart_admin_v2/tomcat-logs
    accesslog:
      enabled: true
      pattern: '%t %{X-Forwarded-For}i %a "%r" %s %D (%D ms)'

#swagger: 提高swagger 方法名称有重复的日志提示
logging:
  level:
    springfox:
      documentation:
        spring:
          web:
            readers:
              operation:
                CachingOperationNameGenerator: warn
            scanners:
              ApiListingReferenceScanner: warn

# 文件上传 配置
file:
  storage:
    mode: cloud
    local:
      path: ${localPath:/home}/smart_admin_v2/upload/
    cloud:
      region: oss-cn-qingdao
      endpoint: oss-cn-qingdao.aliyuncs.com
      bucket-name: common-sit
      access-key:
      secret-key:
      url:
        expire: 7200000
        public: https://${file.storage.cloud.bucket-name}.${file.storage.cloud.endpoint}/

# swagger 配置
swagger:
  title: SmartAdmin
  description: SmartAdmin 2.0
  version: 2.0
  host: localhost:${server.port}
  package: net.lab1024.sa
  tag-class: net.lab1024.sa.common.constant.SwaggerTagConst
  team-url: https://www.1024lab.net/

# RestTemplate 请求配置
http:
  pool:
    max-total: 20
    connect-timeout: 50000
    read-timeout: 50000
    write-timeout: 50000
    keep-alive: 300000

# token相关配置
token:
  key: sa-jwt-key
  expire-day: 7

# 跨域配置
access-control-allow-origin: '*'

# 心跳配置
heart-beat:
  interval-seconds: 60

# 热加载配置
reload:
  interval-seconds: 60